<a href="https://colab.research.google.com/github/leticiamendes-data/rio-plan/blob/main/analise/analise_viagem_rio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

In [9]:
import os

os.listdir()

['.config', 'gastos-viagem.csv', 'sample_data']

In [14]:
gastos = pd.read_csv("gastos-viagem.csv")
gastos.head()

         Data              Descricao Categoria    Forma   Valor  Observacao
0  2026-09-09                Padaria    Comida  Credito  -37.47         NaN
1  2026-09-09     Dumare Restaurante    Comida  Credito -135.89         NaN
2  2026-09-09  Pao de Acucar Mercado   Mercado  Credito  -37.14         NaN
3  2026-09-09          The Best Acai    Comida  Credito  -29.77         NaN
4  2026-09-10      Embaixada Carioca    Comida  Credito  -85.12         NaN

In [15]:
import requests

url = "https://archive-api.open-meteo.com/v1/archive"
parametros = {
    "latitude": -22.9068,
    "longitude": -43.1729,
    "start_date": "2026-09-09",
    "end_date": "2026-09-15",
    "daily": ["temperature_2m_max", "temperature_2m_min", "precipitation_sum", "weathercode"],
    "timezone": "America/Sao_Paulo",
}

resposta = requests.get(url, params=parametros)
dados_clima = resposta.json()

clima = pd.DataFrame(dados_clima["daily"])
clima

,time,temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode
0,2026-09-09,22.8,19.7,4.7,61
1,2026-09-10,25.8,21.1,31.6,65
2,2026-09-11,26.2,21.1,7.3,61
3,2026-09-12,26.0,21.7,3.2,53
4,2026-09-13,21.7,19.0,8.4,61
5,2026-09-14,22.8,18.8,16.2,63
6,2026-09-15,21.8,19.1,2.8,61